server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        generate_statistics: "false"
        format_sql: "true"
        ddl-auto: "none"
        hbm2ddl:
          auto: "none"
    show-sql: true
    database-platform: "org.hibernate.dialect.H2Dialect"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ibmspringboot@gmail.com
    password: ibmpractica2022
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org:
      hibernate:
        stat: debug
        type: debug
